from datetime import datetime, timezone
from fastapi import APIRouter, Depends, HTTPException, status
from fastapi.responses import PlainTextResponse
from sqlalchemy.orm import Session
from backend.app.core.database import get_db
from backend.app.models.lot import Lot
from backend.app.models.component import Component
from backend.app.api.deps import get_current_user

router = APIRouter(prefix="/reports", tags=["Inspection Reports & QA Summary"])

@router.get("/lot/{lot_id}/summary")
def get_lot_inspection_report(lot_id: str, db: Session = Depends(get_db), current_user = Depends(get_current_user)):
    lot = db.query(Lot).filter(Lot.lot_id == lot_id).first()
    if not lot:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail=f"Lot '{lot_id}' not found.")

    comps = db.query(Component).filter(Component.lot_id == lot_id).all()
    total = len(comps)
    passed = sum(1 for c in comps if c.status == "PASS")
    review = sum(1 for c in comps if c.status == "REVIEW")
    rejected = sum(1 for c in comps if c.status == "REJECT")
    escaped = sum(1 for c in comps if c.status == "PASS" and c.is_ground_truth_defect)

    return {
        "report_id": f"REP-{lot_id}-{datetime.now(timezone.utc).strftime('%Y%m%d%H%M')}",
        "generated_at": datetime.now(timezone.utc).isoformat(),
        "generated_by": current_user.username,
        "lot_id": lot_id,
        "part_family": lot.part_family,
        "burn_in_chamber_temp_c": 125.0,
        "total_components": total,
        "screening_results": {
            "pass": passed,
            "review": review,
            "reject": rejected,
            "yield_rate_percent": round((passed / max(total, 1)) * 100.0, 2),
            "escaped_defects": escaped,
            "time_saved_hours": rejected * 144.0
        },
        "lot_baselines": {
            "median_iddq": lot.median_iddq,
            "mad_iddq": lot.mad_iddq,
            "safety_slope": lot.safety_slope
        },
        "certification_statement": (
            "This report was automatically synthesized by BurnWatch 3D AI Screening Engine in accordance "
            "with ISRO High-Reliability Spacecraft Component Environmental Stress Screening guidelines."
        )
    }

@router.get("/lot/{lot_id}/markdown", response_class=PlainTextResponse)
def get_lot_report_markdown(lot_id: str, db: Session = Depends(get_db), current_user = Depends(get_current_user)):
    rep = get_lot_inspection_report(lot_id, db, current_user)
    sr = rep["screening_results"]
    lb = rep["lot_baselines"]

    md = f"""# ISRO QA Screening Inspection Report
**Report ID**: `{rep['report_id']}`  
**Lot ID**: `{rep['lot_id']}`  
**Part Family**: `{rep['part_family']}`  
**Generated By**: `{rep['generated_by']}` at `{rep['generated_at']}`  
**Burn-In Temperature**: `125°C` (Arrhenius Stress Acceleration)

---

## 1. Executive Screening Summary
- **Total Tested Components**: {rep['total_components']}
- **Certified Flight Pass**: {sr['pass']} ({sr['yield_rate_percent']}%)
- **Suspect (Under Review)**: {sr['review']}
- **Rejected (Latent / Drift Defect)**: {sr['reject']}
- **Escaped Defects (False Negatives)**: **{sr['escaped_defects']}** (Critical Safety Metric)
- **Burn-In Oven Time Saved**: {sr['time_saved_hours']} Chamber Hours

## 2. Dynamic Baselines
- **Lot Median Iddq**: {lb['median_iddq']} µA
- **Lot MAD**: {lb['mad_iddq']} µA
- **Calculated Safety Slope**: {lb['safety_slope']} µA/h

## 3. Compliance Certification
{rep['certification_statement']}
"""
    return PlainTextResponse(md, media_type="text/markdown")
