"""create_burnwatch_tables

Revision ID: 4250e193f516
Revises: 
Create Date: 2026-10-05 19:32:59.421709

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4250e193f516'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('old_value_json', sa.Text(), nullable=True),
    sa.Column('new_value_json', sa.Text(), nullable=True),
    sa.Column('details_json', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('idx_audit_res_ts', ['resource_type', 'resource_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_id'), ['resource_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_user_id'), ['user_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_username'), ['username'], unique=False)

    op.create_table('lots',
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('part_family', sa.String(length=50), nullable=True),
    sa.Column('wafer_id', sa.String(length=50), nullable=True),
    sa.Column('fabrication_date', sa.String(length=20), nullable=True),
    sa.Column('total_parts', sa.Integer(), nullable=True),
    sa.Column('screened_parts', sa.Integer(), nullable=True),
    sa.Column('anomaly_count', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('burn_in_duration_hours', sa.Integer(), nullable=True),
    sa.Column('median_iddq', sa.Float(), nullable=True),
    sa.Column('mad_iddq', sa.Float(), nullable=True),
    sa.Column('median_slope', sa.Float(), nullable=True),
    sa.Column('safety_slope', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('lot_id')
    )
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_lots_lot_id'), ['lot_id'], unique=False)

    op.create_table('model_versions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version_tag', sa.String(length=50), nullable=False),
    sa.Column('model_family', sa.String(length=50), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('hyperparameters_json', sa.Text(), nullable=True),
    sa.Column('metrics_json', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('trained_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_model_versions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_is_active'), ['is_active'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_model_family'), ['model_family'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_trained_at'), ['trained_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_model_versions_version_tag'), ['version_tag'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=100), nullable=True),
    sa.Column('role', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_username'), ['username'], unique=True)

    op.create_table('components',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('part_id', sa.String(length=60), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('family', sa.String(length=50), nullable=True),
    sa.Column('wafer_id', sa.String(length=50), nullable=True),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('col', sa.Integer(), nullable=True),
    sa.Column('tray_x', sa.Float(), nullable=True),
    sa.Column('tray_y', sa.Float(), nullable=True),
    sa.Column('tray_z', sa.Float(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_ground_truth_defect', sa.Boolean(), nullable=True),
    sa.Column('defect_type', sa.String(length=50), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['lot_id'], ['lots.lot_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_components_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_components_part_id'), ['part_id'], unique=True)

    op.create_table('measurements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('v_0h', sa.Float(), nullable=False),
    sa.Column('v_24h', sa.Float(), nullable=False),
    sa.Column('v_96h', sa.Float(), nullable=True),
    sa.Column('v_168h', sa.Float(), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('quality_status', sa.String(length=30), nullable=True),
    sa.Column('temperature_c', sa.Float(), nullable=True),
    sa.Column('voltage_v', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.create_index('idx_meas_comp_ts', ['component_id', 'timestamp'], unique=False)
        batch_op.create_index('idx_meas_param_ts', ['parameter', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_parameter'), ['parameter'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_quality_status'), ['quality_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_measurements_timestamp'), ['timestamp'], unique=False)

    op.create_table('qa_decisions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('inspector_id', sa.Integer(), nullable=False),
    sa.Column('inspector_username', sa.String(length=50), nullable=False),
    sa.Column('original_verdict', sa.String(length=20), nullable=False),
    sa.Column('final_verdict', sa.String(length=20), nullable=False),
    sa.Column('override_reason', sa.Text(), nullable=True),
    sa.Column('is_override', sa.Boolean(), nullable=True),
    sa.Column('decision_timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.ForeignKeyConstraint(['inspector_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('qa_decisions', schema=None) as batch_op:
        batch_op.create_index('idx_qa_lot_comp', ['lot_id', 'component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_decisions_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_decisions_decision_timestamp'), ['decision_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_decisions_final_verdict'), ['final_verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_decisions_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_qa_decisions_lot_id'), ['lot_id'], unique=False)

    op.create_table('screening_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('screening_run_id', sa.String(length=80), nullable=True),
    sa.Column('component_id', sa.Integer(), nullable=False),
    sa.Column('lot_id', sa.String(length=50), nullable=False),
    sa.Column('parameter', sa.String(length=30), nullable=False),
    sa.Column('checkpoint', sa.Integer(), nullable=True),
    sa.Column('static_verdict', sa.String(length=20), nullable=True),
    sa.Column('dynamic_verdict', sa.String(length=20), nullable=True),
    sa.Column('drift_verdict', sa.String(length=20), nullable=True),
    sa.Column('final_verdict', sa.String(length=20), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('robust_z_score', sa.Float(), nullable=True),
    sa.Column('iqr_score', sa.Float(), nullable=True),
    sa.Column('iforest_score', sa.Float(), nullable=True),
    sa.Column('ensemble_score', sa.Float(), nullable=True),
    sa.Column('predicted_168h', sa.Float(), nullable=True),
    sa.Column('drift_slope', sa.Float(), nullable=True),
    sa.Column('safety_slope', sa.Float(), nullable=True),
    sa.Column('early_reject_flag', sa.Boolean(), nullable=True),
    sa.Column('time_saved_hours', sa.Float(), nullable=True),
    sa.Column('plain_english_justification', sa.Text(), nullable=True),
    sa.Column('shap_values_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['component_id'], ['components.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.create_index('idx_scr_comp_verdict', ['component_id', 'final_verdict'], unique=False)
        batch_op.create_index('idx_scr_lot_chkpt', ['lot_id', 'checkpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_checkpoint'), ['checkpoint'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_component_id'), ['component_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_final_verdict'), ['final_verdict'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_lot_id'), ['lot_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_parameter'), ['parameter'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_results_screening_run_id'), ['screening_run_id'], unique=False)

    with op.batch_alter_table('ai_inferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('sequence',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
        batch_op.alter_column('sequence',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.alter_column('sequence',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('ai_inferences', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)

    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_results_screening_run_id'))
        batch_op.drop_index(batch_op.f('ix_screening_results_parameter'))
        batch_op.drop_index(batch_op.f('ix_screening_results_lot_id'))
        batch_op.drop_index(batch_op.f('ix_screening_results_id'))
        batch_op.drop_index(batch_op.f('ix_screening_results_final_verdict'))
        batch_op.drop_index(batch_op.f('ix_screening_results_created_at'))
        batch_op.drop_index(batch_op.f('ix_screening_results_component_id'))
        batch_op.drop_index(batch_op.f('ix_screening_results_checkpoint'))
        batch_op.drop_index('idx_scr_lot_chkpt')
        batch_op.drop_index('idx_scr_comp_verdict')

    op.drop_table('screening_results')
    with op.batch_alter_table('qa_decisions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_qa_decisions_lot_id'))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_id'))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_final_verdict'))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_decision_timestamp'))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_component_id'))
        batch_op.drop_index('idx_qa_lot_comp')

    op.drop_table('qa_decisions')
    with op.batch_alter_table('measurements', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_measurements_timestamp'))
        batch_op.drop_index(batch_op.f('ix_measurements_quality_status'))
        batch_op.drop_index(batch_op.f('ix_measurements_parameter'))
        batch_op.drop_index(batch_op.f('ix_measurements_id'))
        batch_op.drop_index(batch_op.f('ix_measurements_created_at'))
        batch_op.drop_index(batch_op.f('ix_measurements_component_id'))
        batch_op.drop_index('idx_meas_param_ts')
        batch_op.drop_index('idx_meas_comp_ts')

    op.drop_table('measurements')
    with op.batch_alter_table('components', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_components_part_id'))
        batch_op.drop_index(batch_op.f('ix_components_lot_id'))
        batch_op.drop_index(batch_op.f('ix_components_id'))

    op.drop_table('components')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_username'))
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_email'))

    op.drop_table('users')
    with op.batch_alter_table('model_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_model_versions_version_tag'))
        batch_op.drop_index(batch_op.f('ix_model_versions_trained_at'))
        batch_op.drop_index(batch_op.f('ix_model_versions_model_family'))
        batch_op.drop_index(batch_op.f('ix_model_versions_is_active'))
        batch_op.drop_index(batch_op.f('ix_model_versions_id'))

    op.drop_table('model_versions')
    with op.batch_alter_table('lots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lots_lot_id'))

    op.drop_table('lots')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_audit_logs_username'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_user_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('idx_audit_res_ts')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
