"""add_traceability_and_versioning_columns

Revision ID: be740fb43a1a
Revises: 4250e193f516
Create Date: 2026-10-05 21:01:49.448222

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'be740fb43a1a'
down_revision: Union[str, Sequence[str], None] = '4250e193f516'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_anomaly_events_trace_id'), ['trace_id'], unique=False)

    with op.batch_alter_table('qa_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('justification', sa.Text(), nullable=False, server_default=''))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_index(batch_op.f('idx_qa_lot_comp'))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_decision_timestamp'))
        batch_op.create_index(batch_op.f('ix_qa_decisions_created_at'), ['created_at'], unique=False)
        batch_op.drop_column('decision_timestamp')
        batch_op.drop_column('override_reason')
        batch_op.drop_column('is_override')

    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('inference_id', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('confidence', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('model_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('feature_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('threshold_version', sa.String(length=50), nullable=True))
        batch_op.create_index(batch_op.f('ix_screening_results_inference_id'), ['inference_id'], unique=True)

    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trace_id', sa.String(length=64), nullable=True))
        batch_op.create_index(batch_op.f('ix_telemetry_events_trace_id'), ['trace_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('telemetry_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_telemetry_events_trace_id'))
        batch_op.drop_column('trace_id')

    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_results_inference_id'))
        batch_op.drop_column('threshold_version')
        batch_op.drop_column('feature_version')
        batch_op.drop_column('model_version')
        batch_op.drop_column('confidence')
        batch_op.drop_column('inference_id')

    with op.batch_alter_table('qa_decisions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_override', sa.BOOLEAN(), nullable=True))
        batch_op.add_column(sa.Column('override_reason', sa.TEXT(), nullable=True))
        batch_op.add_column(sa.Column('decision_timestamp', sa.DATETIME(), nullable=True))
        batch_op.drop_index(batch_op.f('ix_qa_decisions_created_at'))
        batch_op.create_index(batch_op.f('ix_qa_decisions_decision_timestamp'), ['decision_timestamp'], unique=False)
        batch_op.create_index(batch_op.f('idx_qa_lot_comp'), ['lot_id', 'component_id'], unique=False)
        batch_op.drop_column('created_at')
        batch_op.drop_column('justification')

    with op.batch_alter_table('anomaly_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_anomaly_events_trace_id'))
        batch_op.drop_column('trace_id')

    # ### end Alembic commands ###
