"""add_canonical_realtime_events_and_worker_leases

Revision ID: fc0877dfaef0
Revises: be740fb43a1a
Create Date: 2026-10-05 21:30:12.666965

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fc0877dfaef0'
down_revision: Union[str, Sequence[str], None] = 'be740fb43a1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Check if realtime_events exists; if not, create it
    conn = op.get_bind()
    inspector = sa.inspect(conn)
    tables = inspector.get_table_names()
    if 'realtime_events' not in tables:
        op.create_table(
            'realtime_events',
            sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
            sa.Column('event_id', sa.String(length=64), nullable=False),
            sa.Column('trace_id', sa.String(length=64), nullable=True),
            sa.Column('sequence', sa.Integer(), nullable=False),
            sa.Column('event_type', sa.String(length=50), nullable=False),
            sa.Column('schema_version', sa.Integer(), nullable=True, server_default='2'),
            sa.Column('timestamp', sa.DateTime(), nullable=False),
            sa.Column('server_timestamp', sa.DateTime(), nullable=True),
            sa.Column('lot_id', sa.String(length=50), nullable=True),
            sa.Column('component_id', sa.String(length=60), nullable=True),
            sa.Column('chamber_id', sa.String(length=50), nullable=True, server_default='CH-01'),
            sa.Column('payload_json', sa.Text(), nullable=False),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.PrimaryKeyConstraint('id')
        )
        with op.batch_alter_table('realtime_events', schema=None) as batch_op:
            batch_op.create_index(batch_op.f('ix_realtime_events_id'), ['id'], unique=False)
            batch_op.create_index(batch_op.f('ix_realtime_events_event_id'), ['event_id'], unique=True)
            batch_op.create_index(batch_op.f('ix_realtime_events_sequence'), ['sequence'], unique=True)
            batch_op.create_index(batch_op.f('ix_realtime_events_event_type'), ['event_type'], unique=False)
            batch_op.create_index(batch_op.f('ix_realtime_events_trace_id'), ['trace_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_realtime_events_lot_id'), ['lot_id'], unique=False)
            batch_op.create_index(batch_op.f('ix_realtime_events_component_id'), ['component_id'], unique=False)
            batch_op.create_index('idx_rte_lot_seq', ['lot_id', 'sequence'], unique=False)
            batch_op.create_index('idx_rte_type_seq', ['event_type', 'sequence'], unique=False)
            batch_op.create_index('idx_rte_ts', ['timestamp'], unique=False)

    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.add_column(sa.Column('model_component_status', sa.String(length=30), nullable=True, server_default='ACTIVE'))
        batch_op.create_unique_constraint('uq_screening_run_comp_chkpt', ['screening_run_id', 'component_id', 'checkpoint'])

    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.add_column(sa.Column('worker_id', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('attempt_count', sa.Integer(), nullable=True, server_default='0'))
        batch_op.add_column(sa.Column('heartbeat_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('lease_until', sa.DateTime(), nullable=True))
        batch_op.create_index(batch_op.f('ix_screening_runs_lease_until'), ['lease_until'], unique=False)
        batch_op.create_index(batch_op.f('ix_screening_runs_worker_id'), ['worker_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('screening_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_screening_runs_worker_id'))
        batch_op.drop_index(batch_op.f('ix_screening_runs_lease_until'))
        batch_op.drop_column('lease_until')
        batch_op.drop_column('heartbeat_at')
        batch_op.drop_column('attempt_count')
        batch_op.drop_column('worker_id')

    with op.batch_alter_table('screening_results', schema=None) as batch_op:
        batch_op.drop_constraint('uq_screening_run_comp_chkpt', type_='unique')
        batch_op.drop_column('model_component_status')

    # ### end Alembic commands ###
